"""create tables

Revision ID: d6dde849f65e
Revises: 
Create Date: 2025-03-07 17:20:42.392717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6dde849f65e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoques', sa.Column('id_estoque', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('estoques_roupa_id_fkey', 'estoques', type_='foreignkey')
    op.create_foreign_key(None, 'estoques', 'roupas', ['roupa_id'], ['id_roupa'], ondelete='CASCADE')
    op.drop_column('estoques', 'id')
    op.add_column('roupas', sa.Column('id_roupa', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('roupas', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roupas', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('roupas', 'id_roupa')
    op.add_column('estoques', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'estoques', type_='foreignkey')
    op.create_foreign_key('estoques_roupa_id_fkey', 'estoques', 'roupas', ['roupa_id'], ['id'], ondelete='CASCADE')
    op.drop_column('estoques', 'id_estoque')
    # ### end Alembic commands ###
